import type { Metadata } from "next";
import { Geist_Mono, Urbanist } from "next/font/google";
import SiteCursor from "../components/SiteCursor";
import TransitionOverlay from "../components/TransitionOverlay";
import "./globals.css";

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Afia Zaman — Graphic Designer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${urbanist.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <SiteCursor />
        <TransitionOverlay />
      </body>
    </html>
  );
}
